CREATE TABLESPACE TMP_TPCH DATAFILE 
   SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED,
   SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED,
   SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED,
   SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED,
   SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING DEFAULT COMPRESS EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;

CREATE USER TMP_TPCH IDENTIFIED BY TMP_TPCH 
  DEFAULT TABLESPACE TMP_TPCH PROFILE DEFAULT ACCOUNT UNLOCK;
alter user TMP_TPCH DEFAULT TABLESPACE TMP_TPCH;
ALTER USER TMP_TPCH QUOTA UNLIMITED ON TMP_TPCH;


GRANT connect,resource TO TMP_TPCH;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO TMP_TPCH;

