BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PART';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE PART (
	P_PARTKEY		NUMBER NOT NULL,
	P_NAME			VARCHAR(55),
	P_MFGR			CHAR(25),
	P_BRAND			CHAR(10),
	P_TYPE			VARCHAR(25),
	P_SIZE			INTEGER,
	P_CONTAINER		CHAR(10),
	P_RETAILPRICE	DECIMAL,
	P_COMMENT		VARCHAR(23)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SUPPLIER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE SUPPLIER (
	S_SUPPKEY		NUMBER NOT NULL,
	S_NAME			CHAR(25),
	S_ADDRESS		VARCHAR(40),
	S_NATIONKEY		INTEGER NOT NULL, -- references N_NATIONKEY
	S_PHONE			CHAR(15),
	S_ACCTBAL		DECIMAL,
	S_COMMENT		VARCHAR(101)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PARTSUPP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE PARTSUPP (
	PS_PARTKEY		NUMBER NOT NULL, -- references P_PARTKEY
	PS_SUPPKEY		NUMBER NOT NULL, -- references S_SUPPKEY
	PS_AVAILQTY		INTEGER,
	PS_SUPPLYCOST	DECIMAL,
	PS_COMMENT		VARCHAR(199)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE CUSTOMER (
	C_CUSTKEY		NUMBER NOT NULL,
	C_NAME			VARCHAR(25),
	C_ADDRESS		VARCHAR(40),
	C_NATIONKEY		NUMBER NOT NULL, -- references N_NATIONKEY
	C_PHONE			CHAR(15),
	C_ACCTBAL		DECIMAL,
	C_MKTSEGMENT	CHAR(10),
	C_COMMENT		VARCHAR(117)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ORDERS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE ORDERS (
	O_ORDERKEY		NUMBER NOT NULL,
	O_CUSTKEY		NUMBER NOT NULL, -- references C_CUSTKEY
	O_ORDERSTATUS	CHAR(1),
	O_TOTALPRICE	DECIMAL,
	O_ORDERDATE		DATE,
	O_ORDERPRIORITY	CHAR(15),
	O_CLERK			CHAR(15),
	O_SHIPPRIORITY	INTEGER,
	O_COMMENT		VARCHAR(79)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LINEITEM';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE LINEITEM (
	L_ORDERKEY		NUMBER NOT NULL, -- references O_ORDERKEY
	L_PARTKEY		NUMBER NOT NULL, -- references P_PARTKEY (compound fk to PARTSUPP)
	L_SUPPKEY		NUMBER NOT NULL, -- references S_SUPPKEY (compound fk to PARTSUPP)
	L_LINENUMBER	INTEGER,
	L_QUANTITY		DECIMAL,
	L_EXTENDEDPRICE	DECIMAL,
	L_DISCOUNT		DECIMAL,
	L_TAX			DECIMAL,
	L_RETURNFLAG	CHAR(1),
	L_LINESTATUS	CHAR(1),
	L_SHIPDATE		DATE,
	L_COMMITDATE	DATE,
	L_RECEIPTDATE	DATE,
	L_SHIPINSTRUCT	CHAR(25),
	L_SHIPMODE		CHAR(10),
	L_COMMENT		VARCHAR(44)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE NATION';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE NATION (
	N_NATIONKEY		NUMBER NOT NULL,
	N_NAME			CHAR(25),
	N_REGIONKEY		NUMBER NOT NULL,  -- references R_REGIONKEY
	N_COMMENT		VARCHAR(152)
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE REGION';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


CREATE TABLE REGION (
	R_REGIONKEY	NUMBER NOT NULL,
	R_NAME		CHAR(25),
	R_COMMENT	VARCHAR(152)
);
